easy_admin:
    entities:
        ReferentielEAN:
            templates:
                paginator: '@App/Default/fragments/_showzz.html.twig'
            class: App\Entity\ReferentielEAN
            label: 'Referentiel EAN'
            list:
                sort: ['id', 'ASC']
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - label
                    - databaseName
                    - code
                    - joncture
            show:
                fields:
                    - label
                    - databaseName
                    - code
                    - joncture
            form:
                fields:
                    - label
                    - databaseName
                    - code
                    - joncture
