easy_admin:
    entities:
        Traders:
            templates:
                # Twig namespace template syntax
                paginator: '@App/Default/fragments/_showzz.html.twig'
                # legacy template syntax works too:
                # paginator: 'AppBundle:Default:fragments/_paginator.html.twig'
            class: App\Entity\Trader
            label: 'Commerciaux'
            list:
                sort: ['id', 'ASC']
                actions:
                    - { name: 'show', label: '', icon: 'search' }
                    - { name: 'edit', label: '', icon: 'edit' }
                    - { name: 'delete', label: '', icon: 'trash' }
                fields:
                    - id
                    - code
                    - label
                    - phoneNumber
                    - faxNumber
                    - email
            show:
                fields:
                    - id
                    - code
                    - label
                    - phoneNumber
                    - faxNumber
                    - email
            form:
                fields:
                    - code
                    - label
                    - phoneNumber
                    - faxNumber
                    - email